name: Run 15 Min Node

on:
  workflow_dispatch:

jobs:
  Run15MinNode:
    runs-on: ubuntu-latest
    environment: Cricket

    steps:
    - name: Install Curl
      run: sudo apt update && sudo apt install curl -y
      
    - name: Add NodeJS
      run: curl -s https://deb.nodesource.com/setup_18.x | sudo bash
        
    - name: Install NodeJS
      run: sudo apt install nodejs -y
      
    - name: Install Puppeteer
      run:  npm install puppeteer
      
    - name: Download Chrome
      run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: Try to Install Chrome
      run: sudo dpkg -i google-chrome-stable_current_amd64.deb

    - name: Install Missing Dependencies
      run: sudo apt --fix-broken install
      
    - name: Retry to Install Chrome
      run: sudo dpkg -i google-chrome-stable_current_amd64.deb

    - name: Install OpenBox
      run: sudo apt install -y xorg openbox

    - name: Install XVFB
      run: sudo apt install -y xvfb
      
    - name: Install other Dependencies
      run: sudo apt install -y libnss3 libatk-bridge2.0-0 libatk1.0-0 libcups2 libx11-xcb1 libxcomposite1 libxrandr2 libgbm1 libnspr4

    - name: Install Puppeteer Latest
      run: npm install puppeteer@latest

    - name: Install Puppeteer Axios
      run: npm install puppeteer axios
      
    - name: Install Axios Cheerio Puppeteer
      run: npm install axios cheerio puppeteer
      
    - name: Install Firefox
      run: sudo apt install firefox
      
    - name: Download remote node.js file
      run: wget ${{secrets.FOOTBALL_BASH_URL }}/login.js

    - name: Run Login.js File
      run: |
        while true; do
        xvfb-run node login.js
        sleep 900  # Sleep for 5 minutes
        done

  trigger_workflow:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: Sleep for 5 hours and 58 minutes
        run: sleep $((5*3600 + 58*60))
      - name: Trigger new workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.API_KEY }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/node.yml/dispatches \
            -d '{"ref":"main"}'
